### PR TITLE
fix(embed.js): add title attribute to iframes

### LINKED ISSUE #286: Accessibility: iframe elements are missing a title attribute
**Description**
The embed's iframe element is missing a title attribute.

**To Reproduce**
1. Go to https://blog.adobe.com/en/2020/07/09/prototypes-enhance-remote-design-dev-collaboration.html and inspect the DOM for the video embed
2. Note the missing `title` attribute

**Expected behavior**
Screen reader users rely on a frame title to describe the contents of the frame. Navigating through frame and iframe elements quickly becomes difficult and confusing for users of this technology if the markup does not contain a title attribute.

Screen reader users have the option to pull up a list of titles for all frames on a page. Adding descriptive, unique titles allows users to quickly find the frame they need. If no titles are present, navigating through frames can quickly become difficult and confusing. If no title is listed, screen readers will instead give information like “frame,” “JavaScript,” the filename, or the URL. In most cases, this information won’t be very helpful.

**Proposed solution**
Rewrite the iframe element coming from iframely in `helix-embed`, adding the title attribute.

**Additional context**
- https://github.com/adobe/theblog/issues/331
- https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html

### PR DESCRIPTION
**Pull request by MarquiseRosier**
this adds title attribute to iframes to boost accessibility. Additionally; it ensures that when helix embeds content that does not use iframes a span tag with a title attribute will be included

fix #286

## Related Issues
#286 

Thanks for contributing!

### CODE REVIEW

File: src/embed.js [hunk 1]
```diff
@@ -33,26 +33,37 @@ matchers.push(spotify);
...
+
+  // there is a provider preference, let's go with it.
+  if (oEmbed.html) {
+    const iframe = '<iframe';
+    const titleTerm = 'title=';
+    const iframeIndex = oEmbed.html.indexOf(iframe);
+    const titleIndex = oEmbed.html.indexOf(titleTerm);
+    if (iframeIndex !== -1 && titleIndex === -1) {
+      // eslint-disable-next-line no-param-reassign
+      oEmbed.html = `${oEmbed.html.slice(0, iframeIndex + iframe.length)} title="${title.replace(/"/g, '')}"${oEmbed.html.slice(iframeIndex + iframe.length)}`;
```
Comment (trieloff) [inline src/embed.js:57]: This is very brittle.

Comment (MarquiseRosier) [reply src/embed.js:57]: Great point; ok!

File: src/embed.js [hunk 2]
```diff
@@ -28,18 +28,17 @@ matchers.push(spotify);
...
 
-  if (iframe.length !== 0 && !(iframe.item(0).title)){
-    const body = iframe.item(0).title = title;
-  }
-  else{
-    const span = doc.createElement("span");
+  if (iframe.length !== 0 && !(iframe.item(0).title)) {
+    iframe.item(0).title = title;
+  } else {
+    const span = doc.createElement('span');
```
Comment (trieloff) [inline src/embed.js:41]: Isn't it sufficient to add a `title` attribute? Why do we have to duplicate the content in a span.

Comment (MarquiseRosier) [reply src/embed.js:41]: @trieloff I did this because the code already has this baked in and this is how we seem to prefer to include a title in an embeds html. 

https://github.com/adobe/helix-embed/blob/85b555b356438c88932a7f12c6be1a13ce03b235/src/embed.js#L65-L72

Comment (trieloff) [reply src/embed.js:41]: Ok. I wonder what I've been thinking. But we definitely must add the `title` attribute to the `iframe`.

Comment (MarquiseRosier) [reply src/embed.js:41]: also i think trying to put the attribute in the right place can become a little weird; should we put it where the <script ...> or should we find another element below that like lottieplayer and stick a title attribute in there? That placement would be pretty complex

Comment (MarquiseRosier) [reply src/embed.js:41]: @trieloff no problem that is done! IF we can't find a title we just put "content from <<embed source>>". should I leave the span code?

Comment (trieloff) [reply src/embed.js:41]: Yes, leave the span code, as taking it away would be a breaking change.

**Comment by rofe** [comment]
@MarquiseRosier can this be merged?
